prefix = /usr/local
bindir = $(prefix)/bin
sharedir = $(prefix)/share
mandir = $(sharedir)/man
man1dir = $(mandir)/man1

CFLAGS = --std=c99

all: hithere

clean:
	rm -f main main.o

install: all
	install hellogcs $(DESTDIR)$(bindir)
	install -m 0644 hellogcs.1 $(DESTDIR)$(man1dir)
